# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  pipelines:
    - pipeline: ie-serverside-trigger
      source: ie-serverside
      project: ie-serverside
      trigger: true

trigger:
  - master
  
pool:
  vmImage: ubuntu-latest

steps: 
- script: | 
    echo 'hello world'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    options: 'test -Dsurefire.suiteXmlFiles=db_validation_view.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: 'extent-report'
    downloadPath: '$(Build.ArtifactStagingDirectory)'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/extent-report.zip'
    destinationFolder: '$(Build.ArtifactStagingDirectory)/extent-report'

- task: CmdLine@2
  inputs:
    script: 'npm install -g html-pdf'
  displayName: 'Install HTML Viewer'

- task: CmdLine@2
  inputs:
    script: 'html-pdf $(Build.ArtifactStagingDirectory)/extent-report/ExtentReport.html $(Build.ArtifactStagingDirectory)/extent-report/ExtentReport.pdf'
  displayName: 'Convert HTML to PDF'

- task: CmdLine@2
  inputs:
    script: 'start $(Build.ArtifactStagingDirectory)/extent-report/ExtentReport.pdf'
  displayName: 'View Extent Report'