# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  pipelines:
    - pipeline: ie-serverside-trigger
      source: ie-serverside
      project: ie-serverside
      trigger: true

trigger:
  - master
  
pool:
  vmImage: ubuntu-latest

steps: 
- script: | 
    echo 'hello world'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    options: 'test -Dsurefire.suiteXmlFiles=db_validation_view.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: ExtentReportGeneration@1
  inputs:
    testResultsFormat: 'JUnit'
    reportFilePath: '$(Build.SourcesDirectory)/TestResults/extent-report.html'
    reportTitle: 'My Extent Report'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/TestResults'
    ArtifactName: 'ExtentReport'

- task: InstallExtension@1
  inputs:
    extensionName: 'extent-report-viewer'
    publisherName: 'OpenTest'
    displayName: 'Extent Report Viewer'

- task: DownloadBuildArtifacts@0
  inputs:
    artifactName: 'ExtentReport'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CmdLine@2
  inputs:
    script: 'start $(System.ArtifactsDirectory)/ExtentReport/extent-report.html'