package Models;

import java.util.ArrayList;
import java.util.Arrays;

import Test.Ancera.Test_Variables;

public class ComplexConfigModel {

	public String ComplexThreshold;
	public String HouseThreshold;
	public String LowerLimit;
	public String UpperLimit;

	
	public ComplexConfigModel() {

	}
	
	public static String organizationName = "TestCMSOrg_"+Test_Variables.dateYYYYMMDD;
	public static String organizationFarm1Name = "TestFarm1_"+Test_Variables.dateYYYYMMDD;
	public static String organizationHouse1Name = "TestHouse1_"+Test_Variables.dateYYYYMMDD;
	public static String vaccineName = "SinoVac_"+Test_Variables.dateYYYYMMDD;
	public static String feedName = "SinoFeed_"+Test_Variables.dateYYYYMMDD;
	
	

	
	public static ArrayList<ComplexConfigModel> CreateConfig() {
		ArrayList<ComplexConfigModel> lstComplexConfigModel = new ArrayList<ComplexConfigModel>();
		ComplexConfigModel objTmp = new ComplexConfigModel();

		////////Total OPG Small////////
		objTmp.ComplexThreshold = "50";
		objTmp.HouseThreshold = "50";
		objTmp.LowerLimit = "10000";
		objTmp.UpperLimit = "20000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "20000";
		objTmp.UpperLimit = "30000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "50000";
		objTmp.UpperLimit = "60000";
		lstComplexConfigModel.add(objTmp);	
		
		////////Total OPG Medium////////
		objTmp.ComplexThreshold = "50";
		objTmp.HouseThreshold = "50";
		objTmp.LowerLimit = "10000";
		objTmp.UpperLimit = "20000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "20000";
		objTmp.UpperLimit = "30000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "30000";
		objTmp.UpperLimit = "40000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "50000";
		objTmp.UpperLimit = "60000";
		lstComplexConfigModel.add(objTmp);	
		
		////////Total OPG Large////////
		objTmp.ComplexThreshold = "50";
		objTmp.HouseThreshold = "50";
		objTmp.LowerLimit = "10000";
		objTmp.UpperLimit = "20000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "20000";
		objTmp.UpperLimit = "30000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "30000";
		objTmp.UpperLimit = "40000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "40000";
		objTmp.UpperLimit = "50000";
		lstComplexConfigModel.add(objTmp);	
			
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "50000";
		objTmp.UpperLimit = "60000";
		lstComplexConfigModel.add(objTmp);	
		
		
		////////Total OPG Pullets////////
		objTmp.ComplexThreshold = "50";
		objTmp.HouseThreshold = "50";
		objTmp.LowerLimit = "10000";
		objTmp.UpperLimit = "20000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "60000";
		objTmp.UpperLimit = "70000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "20000";
		objTmp.UpperLimit = "30000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "30000";
		objTmp.UpperLimit = "40000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "40000";
		objTmp.UpperLimit = "50000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "50000";
		objTmp.UpperLimit = "60000";
		lstComplexConfigModel.add(objTmp);	
		
		////////Total OPG Broilers////////
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "10000";
		objTmp.UpperLimit = "20000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "60000";
		objTmp.UpperLimit = "70000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "20000";
		objTmp.UpperLimit = "30000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "30000";
		objTmp.UpperLimit = "40000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "40000";
		objTmp.UpperLimit = "50000";
		lstComplexConfigModel.add(objTmp);	
		
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "50000";
		objTmp.UpperLimit = "60000";
		lstComplexConfigModel.add(objTmp);	
		
		////////large OPG Small////////
		objTmp.ComplexThreshold = "50";
		objTmp.HouseThreshold = "50";
		objTmp.LowerLimit = "10000";
		objTmp.UpperLimit = "20000";
		lstComplexConfigModel.add(objTmp);	
		
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "20000";
		objTmp.UpperLimit = "30000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "30000";
		objTmp.UpperLimit = "40000";
		lstComplexConfigModel.add(objTmp);	

		
		////////Large OPG Medium////////
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "10000";
		objTmp.UpperLimit = "20000";
		lstComplexConfigModel.add(objTmp);	
		
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "20000";
		objTmp.UpperLimit = "30000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "30000";
		objTmp.UpperLimit = "40000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "40000";
		objTmp.UpperLimit = "50000";
		lstComplexConfigModel.add(objTmp);	
		
		
		////////Large OPG Large////////
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "10000";
		objTmp.UpperLimit = "20000";
		lstComplexConfigModel.add(objTmp);	
				
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "20000";
		objTmp.UpperLimit = "30000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "30000";
		objTmp.UpperLimit = "40000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "40000";
		objTmp.UpperLimit = "50000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "50000";
		objTmp.UpperLimit = "60000";
		lstComplexConfigModel.add(objTmp);	
		
		
		////////Large OPG Pullets////////
		objTmp.ComplexThreshold = "50";
		objTmp.HouseThreshold = "50";
		objTmp.LowerLimit = "10000";
		objTmp.UpperLimit = "20000";
		lstComplexConfigModel.add(objTmp);	
			
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "20000";
		objTmp.UpperLimit = "30000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "30000";
		objTmp.UpperLimit = "40000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "40000";
		objTmp.UpperLimit = "50000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "50000";
		objTmp.UpperLimit = "60000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "60000";
		objTmp.UpperLimit = "70000";
		lstComplexConfigModel.add(objTmp);	
		
		////////Large OPG Broiler////////
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "10000";
		objTmp.UpperLimit = "20000";
		lstComplexConfigModel.add(objTmp);	
			
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "60000";
		objTmp.UpperLimit = "70000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "20000";
		objTmp.UpperLimit = "30000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "30000";
		objTmp.UpperLimit = "40000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "40000";
		objTmp.UpperLimit = "50000";
		lstComplexConfigModel.add(objTmp);	
		
		objTmp.ComplexThreshold = "67";
		objTmp.HouseThreshold = "60";
		objTmp.LowerLimit = "50000";
		objTmp.UpperLimit = "60000";
		lstComplexConfigModel.add(objTmp);	
		
		return lstComplexConfigModel;
	}
	
	
	
	public static ArrayList<NormalIngestionModel> FillDataCocci() {
		ArrayList<NormalIngestionModel> lstNormalIngestionModel = new ArrayList<NormalIngestionModel>();	
		NormalIngestionModel objTmp;
		ReportFilters objFilter;
		
		objTmp = new NormalIngestionModel();
		objFilter = new ReportFilters();
		objTmp.TestCaseName = "AN-Coccidia-03: Ingest a run for Coccidia and upload valid sample matrix and verify the result are updated accordingly";
		objTmp.TestCaseDescription = "This test case will verify that uploading valid sample matrix updates results accordingly";
		objTmp.lstFilters = new ArrayList<>();
	    objTmp.pathogen = "Coccidia";
	    objTmp.cartridgeID = "CartridgeCocci"+Test_Variables.date0;
	    objTmp.runStartAssay = true;
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-Cocci-1"+Test_Variables.date0, Test_Variables.dateYYYYMMDD+"-Cocci-2"+Test_Variables.date0, Test_Variables.dateYYYYMMDD+"-Cocci-3"+Test_Variables.date0, Test_Variables.dateYYYYMMDD+"-Cocci-4"+Test_Variables.date0));
		objTmp.fileJson = "[{'LANE':'1','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'1','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'13','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'130','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'130','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'2','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'2','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'103','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'3','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'3','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'130','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'4','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'4','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'103','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'5','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'5','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'143','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'6','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'6','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'163','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'7','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'7','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'173','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'8','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'8','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'183','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'9','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'9','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'193','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'10','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'10','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'193','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'11','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'11','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'113','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''},{'LANE':'12','PATHOGEN':'"+objTmp.pathogen+"','SAMPLEID':'"+objFilter.LstSampleID.get(0)+"','SCANDATETIME':'"+Test_Variables.date100+"','FIGUREOFMERIT':'0','OUTCOME':'','STATUSCODE':'','CALIBRATED_PIPER_COUNTS':'0','COUNT_OUTCOME':'','CARTRIDGEID':'"+objTmp.cartridgeID+"','EXPERIMENTID':'','INSTRUMENTID':'"+Test_Variables.InstrumentID+"','USERID':'"+Test_Variables.UserID+"','RUN_ID':'"+objFilter.LstSampleID.get(0)+"','RUN_TYPE':'SCRIPT_swtest','LANE_NO':'12','DATE':'','TIME':'','LANE_TOTAL_OOCYST_COUNT':'113','LANE_TOTAL_OOCYST_MEAN_INTENSITY':'','LANE_TOTAL_OOCYST_RANGE_INTENSITY':'','LANE_TOTAL_OOCYST_CV_INTENSITY':'','LANE_TOTAL_OOCYST_MEAN_AREA':'','LANE_TOTAL_OOCYST_RANGE_AREA':'','LANE_TOTAL_OOCYST_CV_AREA':'','LANE_TOTAL_OOCYST_MEAN_MAJORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MAJORAXIS':'','LANE_TOTAL_OOCYST_CV_MAJORAXIS':'','LANE_TOTAL_OOCYST_MEAN_MINORAXIS':'','LANE_TOTAL_OOCYST_RANGE_MINORAXIS':'','LANE_TOTAL_OOCYST_CV_MINORAXIS':'','LANE_TOTAL_OOCYST_COUNT_SPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNSPORULATED':'','LANE_TOTAL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_SMALL_OOCYST_COUNT':'13','LANE_SMALL_OOCYST_MEAN_INTENSITY':'','LANE_SMALL_OOCYST_RANGE_INTENSITY':'','LANE_SMALL_OOCYST_CV_INTENSITY':'','LANE_SMALL_OOCYST_MEAN_AREA':'','LANE_SMALL_OOCYST_RANGE_AREA':'','LANE_SMALL_OOCYST_CV_AREA':'','LANE_SMALL_OOCYST_MEAN_MAJORAXIS':'','LANE_SMALL_OOCYST_RANGE_MAJORAXIS':'','LANE_SMALL_OOCYST_CV_MAJORAXIS':'','LANE_SMALL_OOCYST_MEAN_MINORAXIS':'','LANE_SMALL_OOCYST_RANGE_MINORAXIS':'','LANE_SMALL_OOCYST_CV_MINORAXIS':'','LANE_SMALL_OOCYST_COUNT_SPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNSPORULATED':'','LANE_SMALL_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_MEDIUM_OOCYST_COUNT':'13','LANE_MEDIUM_OOCYST_MEAN_INTENSITY':'','LANE_MEDIUM_OOCYST_RANGE_INTENSITY':'','LANE_MEDIUM_OOCYST_CV_INTENSITY':'','LANE_MEDIUM_OOCYST_MEAN_AREA':'','LANE_MEDIUM_OOCYST_RANGE_AREA':'','LANE_MEDIUM_OOCYST_CV_AREA':'','LANE_MEDIUM_OOCYST_MEAN_MAJORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MAJORAXIS':'','LANE_MEDIUM_OOCYST_CV_MAJORAXIS':'','LANE_MEDIUM_OOCYST_MEAN_MINORAXIS':'','LANE_MEDIUM_OOCYST_RANGE_MINORAXIS':'','LANE_MEDIUM_OOCYST_CV_MINORAXIS':'','LANE_MEDIUM_OOCYST_COUNT_SPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNSPORULATED':'','LANE_MEDIUM_OOCYST_COUNT_UNCERTAINSPORULATION':'','LANE_LARGE_OOCYST_COUNT':'120','LANE_LARGE_OOCYST_MEAN_INTENSITY':'','LANE_LARGE_OOCYST_RANGE_INTENSITY':'','LANE_LARGE_OOCYST_CV_INTENSITY':'','LANE_LARGE_OOCYST_MEAN_AREA':'','LANE_LARGE_OOCYST_RANGE_AREA':'','LANE_LARGE_OOCYST_CV_AREA':'','LANE_LARGE_OOCYST_MEAN_MAJORAXIS':'','LANE_LARGE_OOCYST_RANGE_MAJORAXIS':'','LANE_LARGE_OOCYST_CV_MAJORAXIS':'','LANE_LARGE_OOCYST_MEAN_MINORAXIS':'','LANE_LARGE_OOCYST_RANGE_MINORAXIS':'','LANE_LARGE_OOCYST_CV_MINORAXIS':'','LANE_LARGE_OOCYST_COUNT_SPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNSPORULATED':'','LANE_LARGE_OOCYST_COUNT_UNCERTAINSPORULATION':'','STATUS':'','LANE_TOTAL_AREA_UM2':'','LANE_NOISE_AREA_UM2':'','LANE_NOISE_RATIO_PERCENT':'','LANE_NOISE_OBJECT_COUNT':'','LANE_SMALL_NOISE_OBJECT_COUNT':'','LANE_MEDIUM_NOISE_OBJECT_COUNT':'','LANE_LARGE_NOISE_OBJECT_COUNT':'','LANE_EXTRA_LARGE_NOISE_OBJECT_COUNT':'','IMPROC':'ImprocCocc01','VERSION':'"+Test_Variables.ImprocVersion+"','ERROR_CODE':'Exception','IE_COLLECTION_SITE_ID':''}]";
		objTmp.lstFilters.add(objFilter);
		lstNormalIngestionModel.add(objTmp);
		
		return lstNormalIngestionModel;
		}	
	
	
}
