package Models;

import java.util.ArrayList;
import java.util.Arrays;
import Test.Ancera.Test_Variables;

public class RawImageModel {

	public String TestCaseName;
	public String TestCaseDescription;
	public String pathogen;
	public String cartridgeID;
	public int lane;
	public String run_id;
	public String checksum;
	public String base64fileName;
	public String fileName;
	public String InstrumentID;
	public String fileType;
	public ArrayList<ReportFilters> lstFilters;
	public boolean runStartAssay;
	public boolean checkLog;
	public boolean isErrorCode;
	public boolean isPositive;
	public boolean isInstallationRunConfigure;
	public String runMode;
	public String runType;
	public String countOutcome;

	public String totalImages;
	public String startAssay_runID;
	
	public static String fileAbsolutePath = Test_Variables.fileAbsolutePath+"Images\\Salemonella_Test_Dataset_Ancera\\";
	public static String fileAbsolutePathSalm49 = Test_Variables.fileAbsolutePath+"Images\\Salemonella_Test_Dataset\\";
	public static String fileAbsolutePathCocci = Test_Variables.fileAbsolutePath+"Images\\Cocci_Test_Images\\";
	
	public static String checksumValue = "7197adc9b0c93b1aefb11c81f431a68ac53db8e11dd071ca34d8546818b0ec42";
	public static String base64fileValue = "20200820101434_PSN0024_EIM-3320-B0039_L07S01.txt";
	
	public RawImageModel() {

	}

	public static ArrayList<RawImageModel> FillData() {
		ArrayList<RawImageModel> lstRawImageModel = new ArrayList<RawImageModel>();	
		RawImageModel objTmp;
		ReportFilters objFilter;
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20200820101434_PSN0024_EIM-3320-B0039_L07S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20200820101434_PSN0024_EIM-3320-B0039_L07S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		/*
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);

		/*
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		

		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 9;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L09S09.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_9";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 10;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L10S10.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_10";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 11;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L11S11.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_11";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 12;
		objTmp.checksum = checksumValue;
		objTmp.base64fileName = fileAbsolutePath+""+base64fileValue;
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L12S12.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_12";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
					
		/////////////////////////////Installation Run Cases//////////////////////////////////
		/*
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = true;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = true;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);

		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 9;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L09S09.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_9";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 10;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L10S10.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_10";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 11;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L11S11.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_11";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 12;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_L12S12.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Installation";
		objTmp.runMode = "2";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = false;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0+"_12";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		//////////////////////////////Error Code Cases///////////////////////////////////////
	*/		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isInstallationRunConfigure = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-3"+Test_Variables.date0+"_1";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-3"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
	/*
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-3"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = true;
		objTmp.fileType = "";
		objTmp.countOutcome = "E033";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-3"+Test_Variables.date0+"_2";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-3"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		*/
		return lstRawImageModel;
	}	
	
	public static ArrayList<RawImageModel> FillDataSalm() {
		ArrayList<RawImageModel> lstRawImageModel = new ArrayList<RawImageModel>();	
		RawImageModel objTmp;
		ReportFilters objFilter;

		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\SAL-4220_A0194_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\SAL-4220_A0194_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		//
		/*
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);

		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		

		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 9;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L09S09.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_9";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 10;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L10S10.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_10";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 11;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L11S11.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_11";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 12;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_L12S12.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0+"_12";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
				
		//////////////////////////////Error Code Cases///////////////////////////////////////
			
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = "d7c666d8d3ab6cc398e69966acb29f1a53e7a0319337c20a10cb6013ec9bcf0d";
		objTmp.base64fileName = fileAbsolutePath+"base64_salm.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-RI-Salm-2"+Test_Variables.date0+"_L12S12.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = true;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "E033";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-2"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-RI-Salm-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = true;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-RI-Salm-2"+Test_Variables.date0+"_2";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-2"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
	*/
		return lstRawImageModel;
	}
}



