package Models;

import java.util.ArrayList;
import java.util.Arrays;

import Test.Ancera.Test_Variables;

public class RawImageModel {

	public String TestCaseName;
	public String TestCaseDescription;
	public String pathogen;
	public String cartridgeID;
	public int lane;
	public String run_id;
	public String checksum;
	public String base64fileName;
	public String fileName;
	public String InstrumentID;
	public String fileType;
	public ArrayList<ReportFilters> lstFilters;
	public boolean runStartAssay;
	public boolean checkLog;
	public boolean isErrorCode;
	public boolean isPositive;
	public String runMode;
	public String runType;
	public String countOutcome;

	public static String fileAbsolutePath = "C:\\Users\\User\\Downloads\\RawImages\\";
	
	public RawImageModel() {

	}

	public static ArrayList<RawImageModel> FillData() {
		ArrayList<RawImageModel> lstRawImageModel = new ArrayList<RawImageModel>();	
		RawImageModel objTmp;
		ReportFilters objFilter;

		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = "0113874a55889c461f7468d0900358e3da182072b7c250f16400982be26a22a5";
		objTmp.base64fileName = fileAbsolutePath+"base64_1.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = true;
		objTmp.checkLog = true;
		objTmp.isErrorCode = false;
		objTmp.isPositive = true;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
//		OBJTMP = NEW RAWIMAGEMODEL();
//		OBJFILTER = NEW REPORTFILTERS();
//		OBJTMP.LSTFILTERS = NEW ARRAYLIST<>();
//		OBJTMP.PATHOGEN = "COCCIDIA";
//		OBJTMP.CARTRIDGEID = "TESTCARTRIDGE-"+TEST_VARIABLES.DATE0;
//		OBJTMP.LANE = 2;
//		OBJTMP.CHECKSUM = "0D1AE6019A4428F48CBD78306C6AC17472409415A8FDF2954917ADF72D5B4EAA";
//		OBJTMP.BASE64FILENAME = FILEABSOLUTEPATH+"BASE64_2.TXT";
//		OBJTMP.FILENAME = TEST_VARIABLES.DATEYYYYMMDD+"-TESTAUT-1"+TEST_VARIABLES.DATE0+"_L02S02.BMP";
//		OBJTMP.INSTRUMENTID = "PSN0001";
//		OBJTMP.RUNTYPE = "NORMAL";
//		OBJTMP.RUNMODE = "1";
//		OBJTMP.RUNSTARTASSAY = FALSE;
//		OBJTMP.CHECKLOG = FALSE;
//		OBJTMP.ISERRORCODE = FALSE;
//		OBJTMP.ISPOSITIVE = TRUE;
//		OBJTMP.FILETYPE = "bmp";
//		OBJTMP.COUNTOUTCOME = "";
//		OBJTMP.RUN_ID = TEST_VARIABLES.DATEYYYYMMDD+"-TESTAUT-1"+TEST_VARIABLES.DATE0+"_2";		
//		OBJFILTER.LSTSAMPLEID = NEW ARRAYLIST<>(ARRAYS.ASLIST(TEST_VARIABLES.DATEYYYYMMDD+"-TESTAUT-1"+TEST_VARIABLES.DATE0));
//		OBJTMP.LSTFILTERS.ADD(OBJFILTER);
//		LSTRAWIMAGEMODEL.ADD(OBJTMP);
//		
//		OBJTMP = NEW RAWIMAGEMODEL();
//		OBJFILTER = NEW REPORTFILTERS();
//		OBJTMP.LSTFILTERS = NEW ARRAYLIST<>();
//		OBJTMP.PATHOGEN = "COCCIDIA";
//		OBJTMP.CARTRIDGEID = "TESTCARTRIDGE-"+TEST_VARIABLES.DATE0;
//		OBJTMP.LANE = 3;
//		OBJTMP.CHECKSUM = "0D1AE6019A4428F48CBD78306C6AC17472409415A8FDF2954917ADF72D5B4EAA";
//		OBJTMP.BASE64FILENAME = FILEABSOLUTEPATH+"BASE64_2.TXT";
//		OBJTMP.FILENAME = TEST_VARIABLES.DATEYYYYMMDD+"-TESTAUT-1"+TEST_VARIABLES.DATE0+"_L03S03.BMP";
//		OBJTMP.INSTRUMENTID = "PSN0001";
//		OBJTMP.RUNTYPE = "NORMAL";
//		OBJTMP.RUNMODE = "1";
//		OBJTMP.RUNSTARTASSAY = FALSE;
//		OBJTMP.CHECKLOG = TRUE;
//		OBJTMP.ISERRORCODE = FALSE;
//		OBJTMP.ISPOSITIVE = TRUE;
//		OBJTMP.FILETYPE = "bmp";
//		OBJTMP.COUNTOUTCOME = "";
//		OBJTMP.RUN_ID = TEST_VARIABLES.DATEYYYYMMDD+"-TESTAUT-1"+TEST_VARIABLES.DATE0+"_3";		
//		OBJFILTER.LSTSAMPLEID = NEW ARRAYLIST<>(ARRAYS.ASLIST(TEST_VARIABLES.DATEYYYYMMDD+"-TESTAUT-1"+TEST_VARIABLES.DATE0));
//		OBJTMP.LSTFILTERS.ADD(OBJFILTER);
//		LSTRAWIMAGEMODEL.ADD(OBJTMP);
		

		//////////////////////////////Error Code Cases///////////////////////////////////////
	/*	
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_1";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_2";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_3";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_4";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_5";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_6";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_7";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_8";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);

		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 9;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_9";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 10;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_10";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 11;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_11";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		
		objTmp = new RawImageModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 12;
		objTmp.checksum = "";
		objTmp.base64fileName = "";
		objTmp.fileName = "";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = true;
		objTmp.isPositive = false;
		objTmp.fileType = "";
		objTmp.countOutcome = "E062";
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0+"_12";		
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"-TestAut-1"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageModel.add(objTmp);
		*/
		return lstRawImageModel;
	}	
}

