package Models;

import java.util.ArrayList;
import java.util.Arrays;

import Test.Ancera.Test_Variables;

public class RawImageCompareCountModel {

	public String TestCaseName;
	public String TestCaseDescription;
	public String pathogen;
	public String cartridgeID;
	public int lane;
	public String run_id;
	public String checksum;
	public String base64fileName;
	public String fileName;
	public String InstrumentID;
	public String fileType;
	public ArrayList<ReportFilters> lstFilters;
	public boolean runStartAssay;
	public String startAssay_runID;
	public boolean checkLog;
	public boolean isErrorCode;
	public boolean isPositive;
	public String runMode;
	public String runType;
	public String countOutcome;
	public String totalImages;
	
	public static String fileAbsolutePath = "C:\\Users\\anc_admin\\Downloads\\Salemonella_Test_Dataset_Ancera\\";
	public static String fileAbsolutePathSalm49 = "C:\\Users\\anc_admin\\Downloads\\Salemonella_Test_Dataset\\";
	public static String fileAbsolutePathCocci = "C:\\Users\\anc_admin\\Downloads\\Cocci_Test_Images\\";
	
	
	public RawImageCompareCountModel() {

	}

	public static ArrayList<RawImageCompareCountModel> FillData20() {
		ArrayList<RawImageCompareCountModel> lstRawImageCompareCountModel = new ArrayList<RawImageCompareCountModel>();	
		RawImageCompareCountModel objTmp;
		ReportFilters objFilter;
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4220_A0194_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4220_A0194_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4220_A0195_L06S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4220_A0195_L06S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
	
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4220-A0042_L09S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4220-A0042_L09S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);

		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4220-A0044_L08S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4220-A0044_L08S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4220-A0188_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4220-A0188_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_5_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4220-A0192_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4220-A0192_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_6_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0003_L07S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0003_L07S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_7_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0019_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0019_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_8_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
			
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 9;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0019_L12S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0019_L12S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L09S09.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_9";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_9_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 10;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0021_L06S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0021_L06S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L10S10.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_10";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_10_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 11;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0021_L08S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0021_L08S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L11S11.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_11";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_11_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 12;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0104_L08S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0104_L08S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L12S12.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_12";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_12_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0104_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0104_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = true;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_13_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0109_L07S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0109_L07S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_14_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
	
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0111_L03S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0111_L03S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_15_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);

		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0124_L12S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0124_L12S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_16_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0125_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0125_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_17_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0126_L03S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0126_L03S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_18_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4620-A0126_L07S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4620-A0126_L07S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_19_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
			
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = fileAbsolutePath+"checksum\\SAL-4920-A0051_L05S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePath+"base64\\SAL-4920-A0051_L05S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_20_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		return lstRawImageCompareCountModel;
	}
	
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	public static ArrayList<RawImageCompareCountModel> FillData49() {
		ArrayList<RawImageCompareCountModel> lstRawImageCompareCountModel = new ArrayList<RawImageCompareCountModel>();	
		RawImageCompareCountModel objTmp;
		ReportFilters objFilter;
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\185-L01S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\185-L01S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\214-L12S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\214-L12S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
	
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20200219160557_PSN0013_sal_swtest2_2.1.6.3_L02S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20200219160557_PSN0013_sal_swtest2_2.1.6.3_L02S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);

		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20200219160557_PSN0013_sal_swtest2_2.1.6.3_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20200219160557_PSN0013_sal_swtest2_2.1.6.3_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20200219160557_PSN0013_sal_swtest2_2.1.6.3_L12S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20200219160557_PSN0013_sal_swtest2_2.1.6.3_L12S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_5_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20200304201106_PSN0020_PR000007491-3_L03S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20200304201106_PSN0020_PR000007491-3_L03S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_6_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20200313180744_PSN0004_03132020_PSN4_21612_lis1_L12S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20200313180744_PSN0004_03132020_PSN4_21612_lis1_L12S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_7_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20201204125906_PSN0027_SAL-4220-A0043_L12S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20201204125906_PSN0027_SAL-4220-A0043_L12S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_8_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
			
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 9;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210128165948_PSN0027_SAL-4220-A0060_L01S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210128165948_PSN0027_SAL-4220-A0060_L01S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L09S09.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_9";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_9_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 10;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210128165948_PSN0027_SAL-4220-A0060_L06S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210128165948_PSN0027_SAL-4220-A0060_L06S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L10S10.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_10";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_10_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 11;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210128165948_PSN0027_SAL-4220-A0060_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210128165948_PSN0027_SAL-4220-A0060_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L11S11.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_11";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_11_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 12;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210205163826_PSN0029_SAL-4520-A0051_L06S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210205163826_PSN0029_SAL-4520-A0051_L06S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L12S12.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_12";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_12_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210211162434_PSN0017_SAL-4720-A0061_L06S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210211162434_PSN0017_SAL-4720-A0061_L06S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = true;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_13_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210211162434_PSN0017_SAL-4720-A0061_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210211162434_PSN0017_SAL-4720-A0061_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_14_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
	
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210211162434_PSN0017_SAL-4720-A0061_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210211162434_PSN0017_SAL-4720-A0061_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_15_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);

		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210211162434_PSN0017_SAL-4720-A0061_L12S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210211162434_PSN0017_SAL-4720-A0061_L12S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_16_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210225154959_PSN0022_SAL-0121-A0090_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210225154959_PSN0022_SAL-0121-A0090_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_17_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210225155009_PSN0018_SAL-0121-A0054_L01S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210225155009_PSN0018_SAL-0121-A0054_L01S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "20";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_18_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210225155009_PSN0018_SAL-0121-A0054_L04S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210225155009_PSN0018_SAL-0121-A0054_L04S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_19_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
			
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210225155009_PSN0018_SAL-0121-A0054_L08S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210225155009_PSN0018_SAL-0121-A0054_L08S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_20_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 9;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210225155009_PSN0018_SAL-0121-A0054_L09S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210225155009_PSN0018_SAL-0121-A0054_L09S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L09S09.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_9";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_21_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 10;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210225155009_PSN0018_SAL-0121-A0054_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210225155009_PSN0018_SAL-0121-A0054_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L10S10.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_10";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_22_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 11;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210326080351_PSN0029_SAL-4120-A0091_L06S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210326080351_PSN0029_SAL-4120-A0091_L06S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L11S11.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_11";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_23_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 12;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210406111227_PSN0026_SAL-4720-A0040_L05S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210406111227_PSN0026_SAL-4720-A0040_L05S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L12S12.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_12";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_24_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		
		
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210406111227_PSN0026_SAL-4720-A0040_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210406111227_PSN0026_SAL-4720-A0040_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = true;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_25_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210406112955_PSN0029_SAL-4720-A0058_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210406112955_PSN0029_SAL-4720-A0058_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_26_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
	
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210406113028_PSN0032_SAL-4720-A0044_L02S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210406113028_PSN0032_SAL-4720-A0044_L02S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_27_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);

		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210406113028_PSN0032_SAL-4720-A0044_L06S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210406113028_PSN0032_SAL-4720-A0044_L06S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_28_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210406113028_PSN0032_SAL-4720-A0044_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210406113028_PSN0032_SAL-4720-A0044_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_29_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210406114642_PSN0027_SAL-4720-A0008_L03S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210406114642_PSN0027_SAL-4720-A0008_L03S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_30_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20210514105356_PSN0027_SAL-PR-23PSI_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20210514105356_PSN0027_SAL-PR-23PSI_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_31_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
			
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20211101111829_PSN0006_SAL_20211101_HIP1_L04S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20211101111829_PSN0006_SAL_20211101_HIP1_L04S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_32_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 9;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20211101111829_PSN0006_SAL_20211101_HIP1_L05S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20211101111829_PSN0006_SAL_20211101_HIP1_L05S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L09S09.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_9";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_33_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 10;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20211101111829_PSN0006_SAL_20211101_HIP1_L06S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20211101111829_PSN0006_SAL_20211101_HIP1_L06S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L10S10.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_10";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_34_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 11;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20211101111829_PSN0006_SAL_20211101_HIP1_L07S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20211101111829_PSN0006_SAL_20211101_HIP1_L07S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L11S11.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_11";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_35_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 12;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\20211101111829_PSN0006_SAL_20211101_HIP1_L09S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\20211101111829_PSN0006_SAL_20211101_HIP1_L09S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L12S12.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_3_"+Test_Variables.date0+"_12";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_36_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);

		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\PSN11_blue_1cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\PSN11_blue.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = true;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_37_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\PSN11_blue_200ms_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\PSN11_blue_200ms.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_38_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
	
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\SAL-4120_A0059_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\SAL-4120_A0059_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_39_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);

		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\SAL-4220_A0184_L09S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\SAL-4220_A0184_L09S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_40_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\SAL-4220_A0189_L02S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\SAL-4220_A0189_L02S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_41_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\SAL-4220_A0194_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\SAL-4220_A0194_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_42_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\SAL-4220_A0195_L06S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\SAL-4220_A0195_L06S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_43_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
			
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\SAL-4220_A0196_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\SAL-4220_A0196_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_44_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 9;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\SAL-4220-A0042_L09S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\SAL-4220-A0042_L09S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L09S09.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_9";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_45_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 10;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\white_sample_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\white_sample.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L10S10.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_10";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_46_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 11;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\zeiss2_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\zeiss2.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L11S11.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_11";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_47_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 12;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\zeiss3_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\zeiss3.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_1_"+Test_Variables.date0+"_L12S12.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = false;
		objTmp.checkLog = true;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_4_"+Test_Variables.date0+"_12";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_48_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Salmonella";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePathSalm49+"checksum\\zeiss4_cs.txt";
		objTmp.base64fileName = fileAbsolutePathSalm49+"base64\\zeiss4.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Salm_2_"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.totalImages = "49";
		objTmp.runStartAssay = true;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Salm_5_"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Salm_49_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		return lstRawImageCompareCountModel;
	}
	
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	
	public static ArrayList<RawImageCompareCountModel> FillDataCoccidia() {
		ArrayList<RawImageCompareCountModel> lstRawImageCompareCountModel = new ArrayList<RawImageCompareCountModel>();	
		RawImageCompareCountModel objTmp;
		ReportFilters objFilter;

		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20200820101434_PSN0024_EIM-3320-B0039_L07S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20200820101434_PSN0024_EIM-3320-B0039_L07S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = true;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";	
		objTmp.startAssay_runID = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0;
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
	
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20201120125644_PSN0024_EIM-3420-B0377_L12S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20201120125644_PSN0024_EIM-3420-B0377_L12S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20201120140329_PSN0024_EIM-3420-B0300_L01S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20201120140329_PSN0024_EIM-3420-B0300_L01S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_3_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20201120140329_PSN0024_EIM-3420-B0300_L07S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20201120140329_PSN0024_EIM-3420-B0300_L07S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_4_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210216162031_PSN0021_EIM-5320-B0430_L01S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210216162031_PSN0021_EIM-5320-B0430_L01S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_5_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210303100431_PSN0026_EIM-4820-B0056_L02S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210303100431_PSN0026_EIM-4820-B0056_L02S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_6_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210308123206_PSN0024_EIM-3420-B0295_L05S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210308123206_PSN0024_EIM-3420-B0295_L05S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_7_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210308123206_PSN0024_EIM-3420-B0295_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210308123206_PSN0024_EIM-3420-B0295_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_8_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 9;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210323151112_PSN0033_EIM-3420-B0162_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210323151112_PSN0033_EIM-3420-B0162_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L09S09.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_9";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_9_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 10;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210414181131_PSN0025_EIM-0421-B0013_L12S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210414181131_PSN0025_EIM-0421-B0013_L12S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L10S10.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_10";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_10_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 11;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210414185106_PSN0028_EIM-5120-B0111_L01S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210414185106_PSN0028_EIM-5120-B0111_L01S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L11S11.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_11";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_11_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 12;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210415125050_PSN0028_EIM-5120-B0139_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210415125050_PSN0028_EIM-5120-B0139_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_L12S12.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_1_"+Test_Variables.date0+"_12";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_12_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 1;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210415135255_PSN0031_eim-5120-b0097_L07S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210415135255_PSN0031_eim-5120-b0097_L07S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_L01S01.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = true;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";	
		objTmp.startAssay_runID = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0;
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_1";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_13_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
	
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 2;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210602104253_PSN0033_EIM-5320-B0410_L03S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210602104253_PSN0033_EIM-5320-B0410_L03S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_L02S02.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_2";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_14_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 3;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210623162417_PSN0027_EIM-5320-B0055_L10S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210623162417_PSN0027_EIM-5320-B0055_L10S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_L03S03.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_3";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_15_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 4;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210630171422_PSN0031_EIM-5220-B0039_L09S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210630171422_PSN0031_EIM-5220-B0039_L09S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_L04S04.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_4";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_16_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 5;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210702140542_PSN0031_EIM-5320-B0005_L11S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210702140542_PSN0031_EIM-5320-B0005_L11S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_L05S05.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_5";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_17_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 6;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210716140111_PSN0024_EIM-5320-B0167_L06S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210716140111_PSN0024_EIM-5320-B0167_L06S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_L06S06.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_6";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_18_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 7;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210728172431_PSN0031_EIM-5320-B0043_L04S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210728172431_PSN0031_EIM-5320-B0043_L04S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_L07S07.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_7";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_19_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		objTmp = new RawImageCompareCountModel();
		objFilter = new ReportFilters();
		objTmp.lstFilters = new ArrayList<>();
		objTmp.pathogen = "Coccidia";
		objTmp.cartridgeID = "TestCartridge-"+Test_Variables.date0;
		objTmp.lane = 8;
		objTmp.checksum = fileAbsolutePathCocci+"checksum\\20210915162618_PSN0024_EIM-1021-B0085_L05S01_cs.txt";
		objTmp.base64fileName = fileAbsolutePathCocci+"base64\\20210915162618_PSN0024_EIM-1021-B0085_L05S01.txt";
		objTmp.fileName = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_L08S08.bmp";
		objTmp.InstrumentID = "PSN0001";
		objTmp.runType = "Normal";
		objTmp.runMode = "1";
		objTmp.runStartAssay = false;
		objTmp.checkLog = false;
		objTmp.isErrorCode = false;
		objTmp.fileType = "bmp";
		objTmp.countOutcome = "";		
		objTmp.run_id = Test_Variables.dateYYYYMMDD+"_Cocci_2_"+Test_Variables.date0+"_8";
		objFilter.LstSampleID = new ArrayList<>(Arrays.asList(Test_Variables.dateYYYYMMDD+"_Cocci_20_"+Test_Variables.date0));
		objTmp.lstFilters.add(objFilter);
		lstRawImageCompareCountModel.add(objTmp);
		
		
		return lstRawImageCompareCountModel;
	}
	
}
